name: Test Build and Report to JFrog
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-scan-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - name: Configure npm repo for JFrog
        run: |
          jf npmc --repo-resolve=test-npm-remote --repo-deploy=npm-local
      - name: Install dependencies (resolved through JFrog, build-info collected)
        run: |
          jf npm install --build-name=spring-petclinic --build-number=${{ github.run_number }}
      - name: Build the project (if you have a build step)
        run: |
          jf npm run build --build-name=spring-petclinic  --build-number=${{ github.run_number }} || echo "No build script, skipping"
      - name: Publish build-info to JFrog
        run: |
          jf rt build-collect-env spring-petclinic ${{ github.run_number }}
          jf rt build-add-git vspring-petclinic  ${{ github.run_number }}
          jf rt build-publish spring-petclinic  ${{ github.run_number }}
      - name: Scan build with JFrog Xray
        run: |
          jf build-scan vuln-demo-app ${{ github.run_number }}
